### ISSUE TITLE
slug should be 'form-submissions'

### ISSUE THREAD

**Issue by andr-ec** [payloadcms/plugin-form-builder#10]
The latest version of payload `1.3.0` has a [breaking change](https://github.com/payloadcms/payload/releases/tag/v1.3.0) camelCase slugs will not be auto converted to kebab case anymore.

This will cause a problem when using this plugin and upgrading to version `1.3.0` of payload.

I'm not sure if its best to change or just to link to this issue for visibility.

If a change is going to be made, it should be made here: 

https://github.com/payloadcms/plugin-form-builder/blob/30a70083e29f3b29e36d64a87b0883a76ccd96f7/src/collections/FormSubmissions/index.ts#LL9C57-L9C72

a workaround for anyone else that runs into this issue is adding this 
```
      formSubmissionOverrides: {
        slug: 'form-submissions',
     }
```

**Comment by jacobsfletch** [comment]
@andr-ec great catch! You're exactly right we need to make that change. Do you want to open a PR for this?

**Comment by andr-ec** [comment]
@jacobsfletch gave a couple of possible solutions!
