### ISSUE TITLE
Translate labels

### ISSUE THREAD

**Issue by fabioquarantini** [payloadcms/plugin-form-builder#11]
Hello,
is it possible to translate the labels or other fileds?

Thank you

**Comment by zanami** [comment]
I guess labels should be configurable via formSubmissionOverrides and formOverrides in payload.config.ts
It's just not yet implemented (see [here](https://github.com/payloadcms/plugin-form-builder/blob/main/src/collections/Forms/index.ts#L65) and [here](https://github.com/payloadcms/plugin-form-builder/blob/main/src/collections/FormSubmissions/index.ts#L7)).

This should work but it doesn't
```
    formBuilder({
      formOverrides: {
        labels: {
          singular: {
            en: "Form",
            xx: "Xxxxx",
          },
          plural: {
            en: "Forms",
            xx: "Xxxxxx",
          },
        },
      },

```

**Comment by fabioquarantini** [comment]
I mean the values of the labels like in this image:

[![Payload.png](https://i.postimg.cc/V6sRq52f/Payload.png)](https://postimg.cc/GBNGr3cV)

**Comment by zanami** [comment]
@fabioquarantini Oh I see, that's another story
@jacobsfletch #13 doesn't seem to fix "Forms" and "Form submissions" collections labels translation. Should I start a separate issue?

**Comment by jacobsfletch** [comment]
@fabioquarantini values can be _localized_ using Payload's field localization https://payloadcms.com/docs/configuration/localization#field-by-field-localization. It allows you to save a different value for each of your locales.

@zanami that would be great! Your description above makes sense.
