### ISSUE TITLE
Smaller screen heights hiding field options and search.

### ISSUE THREAD

**Issue by SceptreData** [payloadcms/plugin-form-builder#21]
Very minor issue but I've already had a user contact me about it. At smaller viewport heights I am unable to view all of field options when adding a new field. It also hides the field search bar. 

Example:
![image](https://user-images.githubusercontent.com/15841748/213119985-205ffc80-0f4a-43e8-9581-cb02a5dc6f56.png)

It can get a little funky- sometimes when adjusting the window the select popup flickers back and forth from above the add button to below it. Happening to me on both Chrome and Firefox.

**Comment by jacobsfletch** [comment]
Hey @SceptreData this looks to be an issue with Payload core. Should be totally doable though, we just need to tweak the CSS a bit. If you could open this [there](https://github.com/payloadcms/payload), we could get this taken care of quickly. Thank you!

**Comment by SceptreData** [comment]
I'll do just that, thanks for getting back to me!
