### ISSUE TITLE
Localization is not managed in `sendEmail` process

### ISSUE THREAD

**Issue by finkinfridom** [payloadcms/plugin-form-builder#32]
As per #31 , the `locale` info is not used when querying `forms` collections. This may lead to scenarios where a missing field on a localized entity is throwing errors but is impossible to spot.

**Comment by finkinfridom** [comment]
If somebody faces the same issue, I published a forked version of this plugin (https://www.npmjs.com/package/@finkinfridom/payload-plugin-form-builder) with the above mentioned fixes.

**Comment by jacobsfletch** [comment]
@finkinfridom I gave a review on #31 just now 👍

**Comment by jacobsfletch** [comment]
This was just published in `1.0.14-canary.0` 🎉

**Comment by jacobsfletch** [comment]
And now `1.0.14` 🚀
