### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by lacruzwebdev** [payloadcms/plugin-form-builder#36]
As soon as I install via npm payload stops working, printing this error in console. I'm guessing there's some dependency that's messing with some other dependency from payload maybe?

![CleanShot 2023-05-11 at 20 20 28](https://github.com/payloadcms/plugin-form-builder/assets/122224251/d66f0c33-7dae-48c5-a97c-804ff4ecfa77)

**Comment by jacobsfletch** [comment]
YES this is absolutely still maintained. What version of Payload are you on? If installing via npm, you may need to run `npm install --save --legacy-peer-deps @payloadcms/plugin-form-builder`.

**Comment by lacruzwebdev** [comment]
It's working perfectly now. It was a dependency then? It could be interesting to place a warning, even if it's a temporary one, in the README.

Thanks a lot Jacob.

**Comment by jacobsfletch** [comment]
This is actually an issue related to Payload core using unresolved version of React, the `peer-deps` flag and `yarn` both automatically resolve these for you, but the permanent fix is here: https://github.com/payloadcms/payload/pull/2656. Once this gets merged in, there shouldn't be any need for this anymore.

**Comment by lacruzwebdev** [comment]
Good to know! Thanks again, Jacob.
