### ISSUE TITLE
Incorrect type definition

### ISSUE THREAD

**Issue by ChristopherNowlan** [payloadcms/plugin-form-builder#37]
[https://github.com/payloadcms/plugin-form-builder/blob/main/src/types.ts](url)

The type definitions for a width is a string should it not be a number? Because when you generate types within a payload project width is set to be a number for form field types

**Comment by ChristopherNowlan** [comment]
No worries. Love the work you and the team are doing on payload

**Comment by jacobsfletch** [comment]
This was just released in `v1.0.14` 🎉
