### ISSUE TITLE
[Feature request] Form submissions export as CSV

### ISSUE THREAD

**Issue by leikoilja** [payloadcms/plugin-form-builder#47]
Now that the form builder plugin helps to build great and easy forms, all data collected ends up in the form submission collection.
It would be amazing to have a feature on that collection (or can be on all collections and used as a general payload feature) to export the entire collection data as `csv` for further processing :)

**Comment by IAmNatch** [comment]
You could implement this yourself by: 
1. [Creating a custom button on the collection page to trigger your export](https://payloadcms.com/docs/admin/components#collections). `BeforeList` would probably be the right place to put it. 
2. Pulling the `data` prop which is passed into your custom component by payload. 
3. Converting the object into a CSV, either manually or with a library. 
4. Trigger a download of the CSV string you've created, using [this approach](https://stackoverflow.com/questions/3665115/how-to-create-a-file-in-memory-for-user-to-download-but-not-through-server).

This should get the job done. If you wanted to go the extra mile, this would make a great payload plugin. Something like `payload-plugin-csv-export`, where you could select which collections you'd like to have this field added to. This would be much more general purpose, and keep the form builder plugin focused on the forms themselves.

**Comment by webmuch** [comment]
@IAmNatch That helped me so much. Thanks! I was simply able to whip this up in half an hour and replicate it across collections:

Here's my code for anyone to reuse:
**The component:**
```
import { Pill } from "payload/components";
import React from "react";
import * as XLSX from "xlsx";

const ExportButton = ({ data }) => {
  console.log(data);
  function handleClick() {
    const worksheet = XLSX.utils.json_to_sheet(data.docs);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Sheet1");
    XLSX.writeFile(workbook, "Data_Export.xlsx");
  }

  return (
    <Pill pillStyle="light" onClick={handleClick}>
      Export
    </Pill>
  );
};

export default ExportButton;
```

The Custom UI for List Page:
```
  admin: {
    components: {
      BeforeListTable: [ExportButton]
    },
  },
```

**Comment by IAmNatch** [comment]
@leikoilja does this resolve your issue?

**Comment by leikoilja** [comment]
sorry, haven't tried it just yet @IAmNatch. Thank you @webmuch for the snippet. I will give it a try soon and close this ticket if it resolves it :)

**Comment by TechSynthesis** [comment]
I tried this out it exports the submissions: id, formName & submissionData id. It doesn't export the contents of submissionData which is what is required. How can I get that to work?

**Comment by Hassiad** [comment]
Thanks @webmuch the solution and code snippet you provided works, also thanks to @IAmNatch for the guide

**Comment by jacobsfletch** [comment]
@webmuch great work 👏  This is currently planned as a Payload core feature, [outlined in our public roadmap here](https://github.com/payloadcms/payload/discussions/4309). Feel free to leave an upvote or comment of support to prioritize that work.

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
