### ISSUE TITLE
Required fields are not validated on submission

### ISSUE THREAD

**Issue by IAmNatch** [payloadcms/plugin-form-builder#60]
**Issue**
Ideally, form values should be validated server-side as well as client side. While the "required" field is passed to the client side, no validation is implemented on the client side. 

**Solution**
This could likely be solved with a beforeValidate hook that fetches the related form, and ensures each required field is present.

**Comment by jacobsfletch** [comment]
Hey @IAmNatch, this might be duplicative of https://github.com/payloadcms/plugin-form-builder/issues/50, what do you think? If you want to leave a comment of support in that issue I will close this one out so we can consolidate the two.

**Comment by jacobsfletch** [comment]
@IAmNatch that would be amazing. Although I _think_ the right way to do this would be to use the normal field-level validations and not a custom hook. We talk about this more in the other ticket or in a PR.
