### ISSUE TITLE
Error after submitting the form on Next.js

### ISSUE THREAD

**Issue by kresogalic8** [payloadcms/plugin-form-builder#68]
I have an error after sending the API request for form-submission which is:

err: "Error while sending one or more emails in form submission id: undefined.

Here is my frontend implementation:

```
const {
    id: formID,
    submitButtonLabel,
    confirmationType,
    redirect,
    fields,
    confirmationMessage,
  } = form
  const [name, email, message, budget, found_us] = fields

  const onSubmit = useCallback(
    (data) => {
      const submitForm = async () => {
        setError(undefined)

        const dataToSend = Object.entries(data).map(([name, value]) => ({
          field: name,
          value,
        }))

        try {
          const req = await fetch(
            `${process.env.NEXT_PUBLIC_CMS_URL}/api/form-submissions`,
            {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                form: formID,
                submissionData: dataToSend,
              }),
            }
          )

          const res = await req.json()

          if (req.status >= 400) {
            setIsLoading(false)
            setError({
              status: res.status,
              message: res.errors?.[0]?.message || 'Internal Server Error',
            })

            return
          }

          setIsLoading(false)
          setHasSubmitted(true)

          if (confirmationType === 'redirect' && redirect) {
            const { url } = redirect

            const redirectUrl = url

            if (redirectUrl) router.push(redirectUrl)
          }
        } catch (err) {
          console.warn(err)
          setIsLoading(false)
          setError({
            message: 'Something went wrong.',
          })
        }
      }

      submitForm()
    },
    [router, formID, redirect, confirmationType]
  )
```

**Comment by matteo-naif** [comment]
Yes, I'm using lexical to write the Confirmation Message and the email message because it's the default in the FormBuilder plugin. 

I found the same error you reported also in the frontend trying to serialize the content of the confirmation message. It seems that now the structure of the object is different, there is an object root that wrap everything so the map cannot works. 

I paste the one I get in the frontend, I resolved serializing the first children property that is an array.

Maybe the problem is the same?

```js
{
    "type": "root",
    "format": "",
    "indent": 0,
    "version": 1,
    "children": [
        {
            "children": [
                {
                    "detail": 0,
                    "format": 0,
                    "mode": "normal",
                    "style": "",
                    "text": "Thanks.",
                    "type": "text",
                    "version": 1
                }
            ],
            "direction": "ltr",
            "format": "",
            "indent": 0,
            "type": "paragraph",
            "version": 1
        }
    ],
    "direction": "ltr"
}```

**Comment by ChristopherNowlan** [comment]
I think the email message is being serialise by slate as far as I can tell from this file [https://github.com/payloadcms/plugin-form-builder/blob/main/src/utilities/serializeRichText.ts](url)

**Comment by jacobsfletch** [comment]
Sounds like some of you are having an issue with Lexical, which is currently _not_ fully supported. There's [an open issue for this here](https://github.com/payloadcms/payload/issues/4475). Feel free to drop a comment of support in there to bump that work. @kresogalic8 if this is _not_ your issue, feel free to open a new ticket in the [Payload monorepo](https://github.com/payloadcms/payload) with more details and ideally a reproduction.

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. Please refer to [this open discussion](https://github.com/payloadcms/payload/discussions/4466) for more details and to continue the conversation.
